### ISSUE TITLE
"react-native windows" issue

### ISSUE THREAD

**Issue by PompolutZ** [ReactWindows/react-native-windows#586]
Hi,

Sorry, I am a bit new to this stuff. When I've tried to follow Getting started guide I've bumped into an issue:

react-native windows
Installing react-native-windows@0.31.*...
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
react-native-windows@0.31.* successfully installed.

Unknown plugin "transform-flow-strip-types" specified in "base" at 0, attempted to resolve relative to "C:\\dev_p\\js\\FirstNative\\node_modules\\react-native-windows\\local-cli"

and then

react-native windows
C:\dev_p\js\FirstNative\node_modules\react-native\node_modules\babel-core\lib\transformation\file\options\option-manager.js:177
          throw new ReferenceError(messages.get("pluginUnknown", plugin, loc, i, dirname));
          ^

ReferenceError: Unknown plugin "transform-flow-strip-types" specified in "base" at 0, attempted to resolve relative to "C:\\dev_p\\js\\FirstNative\\node_modules\\react-native-windows\\local-cli"
    at C:\dev_p\js\FirstNative\node_modules\react-native\node_modules\babel-core\lib\transformation\file\options\option-manager.js:177:17
    at Array.map (native)
    at Function.normalisePlugins (C:\dev_p\js\FirstNative\node_modules\react-native\node_modules\babel-core\lib\transformation\file\options\option-manager.js:153:20)
    at OptionManager.mergeOptions (C:\dev_p\js\FirstNative\node_modules\react-native\node_modules\babel-core\lib\transformation\file\options\option-manager.js:245:36)
    at OptionManager.init (C:\dev_p\js\FirstNative\node_modules\react-native\node_modules\babel-core\lib\transformation\file\options\option-manager.js:383:12)
    at compile (C:\dev_p\js\FirstNative\node_modules\react-native\node_modules\babel-register\lib\node.js:103:45)
    at loader (C:\dev_p\js\FirstNative\node_modules\react-native\node_modules\babel-register\lib\node.js:148:14)
    at Object.require.extensions.(anonymous function) [as .js] (C:\dev_p\js\FirstNative\node_modules\react-native\node_modules\babel-register\lib\node.js:158:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)

Could you please help me to solve this issue?

**Comment by rozele** [comment]
Which version of npm are you using?

**Comment by PompolutZ** [comment]
2.14.12

**Comment by rozele** [comment]
I'm currently using 3.10.5 without issue, is upgrading to the latest node.js an option?

**Comment by PompolutZ** [comment]
omg! thank you so much! it helped :)

**Comment by mpodwysocki** [comment]
@PompolutZ ok to close?
